version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: always
    ports:
      - '9010:8080'
      - '50000:50000'
    volumes:
      - '/usr/local/docker/jenkins/home:/var/jenkins_home'
      - '/usr/java/jdk1.8.0_121:/usr/local/jdk'
      - '/usr/java/apache-maven-3.6.1:/usr/local/maven'
      - '/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime'
      - '/etc/timezone:/etc/timezone'
